### ISSUE TITLE
Website typo

### ISSUE THREAD

**Issue by apowers313** [gilesknap/maaspower#13]
This GitHub page (and several referring links) refers to the switch as the "GS803EP" but it's actually a "GS308EP":
https://gilesknap.github.io/maaspower/main/how-to/web_ui.html

Just sayin 'cause I couldn't figure out where to buy that model of switch at first :)

**Comment by gilesknap** [comment]
Fixed in https://github.com/gilesknap/maaspower/commit/a57eb8e39ddcf67a06e9ebc4a072949cc8e7d5ab
